---
apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  name: "informer"
  namespace: "default"
  labels:
    app: "informer"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "informer"
  template:
    metadata:
      labels:
        app: "informer"
    spec:
      containers:
      - name: "nginx"
        image: "eu.gcr.io/the-informer-213019/appengine"
---
apiVersion: "autoscaling/v1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "informer-hpa"
  namespace: "default"
  labels:
    app: "informer"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "informer"
    apiVersion: "apps/v1beta1"
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
